Table
WildCodeSchool-2024-02/WildCodeSchool-2024-02-JS-Remote-JavaScrypte-P3-FoodTastics pull request #107
Opened 2024-06-19 15:25 UTC by angelique888

2024-06-19 15:25 UTC, AnneDAMIEN approved these changes

2024-06-19 15:28 UTC, yannduhamel approved these changes

2024-06-19 15:30 UTC, enerisan submitted a review, later dismissed

2024-06-20 07:21 UTC, ioayoub approved these changes

2024-06-20 07:52 UTC, Pierre-Voisin submitted a review, later dismissed

2024-06-20 07:53 UTC, Pierre-Voisin approved these changes

2024-06-20 07:53 UTC, yannduhamel submitted a review, later dismissed

2024-06-20 07:54 UTC, AnneDAMIEN approved these changes

2024-06-20 07:55 UTC, enerisan approved these changes

2024-06-20 08:06 UTC, ioayoub requested changes
Update your constraints on your schema.sql.
Actually too much field can have a NULL value.

2024-06-20 08:06 UTC, ioayoub commented on server/database/schema.sql
> +CREATE TABLE user (
- Missing constraints in this table.
- The field comment_quantity is useless here
- about the is_admin field : What if client ask for a third role tomorrow ?

2024-06-20 08:06 UTC, ioayoub commented on server/database/schema.sql
>  CREATE TABLE ingredient (
Missing constraints

2024-06-20 08:06 UTC, ioayoub commented on server/database/schema.sql
>  CREATE TABLE comment (
Missing constraints

2024-06-20 08:50 UTC, closed without merging