US20T02 feat recipe seeder
WildCodeSchool-2024-02/WildCodeSchool-2024-02-JS-Remote-JavaScrypte-P3-FoodTastics pull request #108
Opened 2024-06-19 15:26 UTC by yannduhamel

Create a json file for the basics data of the recipes. The seeder has been done too.

2024-06-19 15:28 UTC, AnneDAMIEN approved these changes

2024-06-19 15:28 UTC, Pierre-Voisin submitted a review, later dismissed

2024-06-19 15:32 UTC, enerisan approved these changes

2024-06-20 07:37 UTC, ioayoub requested changes
Update your schema.sql to handle correctly foreign keys

2024-06-20 09:42 UTC, AnneDAMIEN approved these changes

2024-06-20 09:42 UTC, Pierre-Voisin approved these changes

2024-06-20 09:42 UTC, angelique888 approved these changes

2024-06-20 09:42 UTC, enerisan approved these changes

2024-06-20 09:43 UTC, yannduhamel commented
> Update your schema.sql to handle correctly foreign keys

Angelique has done it in a previous PR, I've edited the users json file to complete the update.

2024-06-20 09:44 UTC, ioayoub approved these changes

2024-06-20 09:45 UTC, merged