US16T04 middleware comment
WildCodeSchool-2024-02/WildCodeSchool-2024-02-JS-Remote-JavaScrypte-P3-FoodTastics pull request #161
Opened 2024-06-29 13:05 UTC by enerisan

2024-06-29 14:43 UTC, yannduhamel submitted a review, later dismissed

2024-06-29 15:54 UTC, AnneDAMIEN approved these changes

2024-06-30 09:02 UTC, Pierre-Voisin approved these changes

2024-07-01 07:09 UTC, angelique888 approved these changes

2024-07-01 13:18 UTC, Pierre-Voisin approved these changes

2024-07-01 13:23 UTC, AnneDAMIEN submitted a review, later dismissed

2024-07-01 13:23 UTC, Pierre-Voisin approved these changes

2024-07-01 14:14 UTC, ioayoub submitted a review, later dismissed

2024-07-01 14:37 UTC, AnneDAMIEN submitted a review, later dismissed

2024-07-01 14:56 UTC, angelique888 submitted a review, later dismissed

2024-07-01 14:57 UTC, yannduhamel submitted a review, later dismissed

2024-07-01 15:25 UTC, Pierre-Voisin approved these changes

2024-07-01 20:11 UTC, ioayoub requested changes

2024-07-01 20:11 UTC, ioayoub commented on server/app/middlewares/validateCommentSchema.js
> +      invalid_type_error: "Votred description n´est pas valide",
typo

2024-07-01 20:11 UTC, ioayoub commented on server/app/middlewares/validateCommentSchema.js
> +      message: "Votre commentaire doit contenir au minimun 2 charactères",
typo in last word

2024-07-01 20:58 UTC, enerisan commented on server/app/middlewares/validateCommentSchema.js
> +      message: "Votre commentaire doit contenir au minimun 2 charactères",
done

2024-07-01 20:58 UTC, enerisan commented on server/app/middlewares/validateCommentSchema.js
> +      invalid_type_error: "Votred description n´est pas valide",
done

2024-07-01 21:03 UTC, ioayoub approved these changes

2024-07-02 06:45 UTC, yannduhamel approved these changes

2024-07-02 07:00 UTC, Pierre-Voisin approved these changes

2024-07-02 07:17 UTC, angelique888 approved these changes

2024-07-02 08:48 UTC, AnneDAMIEN approved these changes

2024-07-02 13:13 UTC, merged