UST01 dashboard utilisateur
WildCodeSchool-2024-02/WildCodeSchool-2024-02-JS-Remote-JavaScrypte-P3-FoodTastics pull request #174
Opened 2024-07-11 19:31 UTC by enerisan

2024-07-11 19:32 UTC, AnneDAMIEN submitted a review, later dismissed

2024-07-12 07:22 UTC, Pierre-Voisin approved these changes

2024-07-12 07:36 UTC, angelique888 submitted a review, later dismissed

2024-07-12 07:36 UTC, yannduhamel submitted a review, later dismissed

2024-07-12 08:03 UTC, ioayoub requested changes

2024-07-12 08:03 UTC, ioayoub commented on client/src/pages/DashboardPage/DashboardPage.css
> +  src: url("../../../public/fonts/NowAlt-Medium.otf");
/fonts/... directly

2024-07-12 08:55 UTC, enerisan commented on client/src/pages/DashboardPage/DashboardPage.css
> +  src: url("../../../public/fonts/NowAlt-Medium.otf");
done :)

2024-07-12 08:56 UTC, Pierre-Voisin approved these changes

2024-07-12 08:56 UTC, angelique888 approved these changes

2024-07-12 08:57 UTC, yannduhamel approved these changes

2024-07-12 08:59 UTC, ioayoub approved these changes

2024-07-12 09:02 UTC, AnneDAMIEN approved these changes

2024-07-12 09:03 UTC, merged