US02 detail recipe
WildCodeSchool-2024-02/WildCodeSchool-2024-02-JS-Remote-JavaScrypte-P3-FoodTastics pull request #177
Opened 2024-07-12 10:40 UTC by angelique888

2024-07-12 10:44 UTC, AnneDAMIEN submitted a review, later dismissed

2024-07-12 10:50 UTC, yannduhamel approved these changes

2024-07-12 13:00 UTC, enerisan submitted a review, later dismissed

2024-07-12 15:52 UTC, ioayoub requested changes

2024-07-12 15:52 UTC, ioayoub commented on client/src/pages/DashboardPage/DashboardPage.jsx
> +  /* // Vérifier si l'utilisateur est connecté à finir
👀

2024-07-13 13:36 UTC, angelique888 commented on client/src/pages/DashboardPage/DashboardPage.jsx
> +  /* // Vérifier si l'utilisateur est connecté à finir
Oups, je viens d'effacer le commentaire et faire un nouveau push.

2024-07-13 14:38 UTC, Pierre-Voisin approved these changes

2024-07-13 18:11 UTC, enerisan submitted a review, later dismissed

2024-07-15 07:20 UTC, ioayoub submitted a review, later dismissed

2024-07-15 08:00 UTC, ioayoub submitted a review, later dismissed

2024-07-15 14:20 UTC, enerisan approved these changes

2024-07-15 14:22 UTC, yannduhamel approved these changes

2024-07-15 14:24 UTC, enerisan approved these changes

2024-07-15 14:24 UTC, merged