fix: add toastify on connection page
WildCodeSchool-2024-02/WildCodeSchool-2024-02-JS-Remote-JavaScrypte-P3-FoodTastics pull request #195
Opened 2024-07-23 13:04 UTC by AnneDAMIEN

2024-07-23 13:31 UTC, yannduhamel submitted a review, later dismissed

2024-07-23 13:44 UTC, Pierre-Voisin submitted a review, later dismissed

2024-07-23 14:06 UTC, ioayoub requested changes

2024-07-23 14:06 UTC, ioayoub commented on client/src/components/Connection/Connection.jsx
> +import "react-toastify/dist/ReactToastify.css";
you can import this directly in your App.jsx to avoid duplications

2024-07-23 16:31 UTC, enerisan approved these changes

2024-07-23 17:54 UTC, yannduhamel approved these changes

2024-07-24 07:58 UTC, ioayoub approved these changes

2024-07-24 10:14 UTC, merged